[package]
name = "wildly-unqualified-desktop"
version = "0.1.0-alpha.1"
edition = "2021"

[[bin]]
name = "wildly-unqualified"
path = "src/main.rs"

[build-dependencies]
tauri-build = "=2.6.3"

[dependencies]
tauri = { version = "=2.11.5", features = ["custom-protocol"] }
serde_json = "1"
windows-sys = { version = "0.61", features = ["Win32_UI_WindowsAndMessaging"] }

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
strip = true
panic = "abort"
